# Generated by Django 4.2.5 on 2023-11-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://d2v9ipibika81v.cloudfront.net/uploads/sites/210/Profile-Icon.png', upload_to='proifile_pics'),
        ),
    ]
